pipeline:
  name: lambda-function-cicd
  identifier: lambdafunctioncicd
  projectIdentifier: lambda
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githupharness
        repoName: lambda-demo
        build: <+input>
  variables:
    - name: layer_arn
      type: String
      description: Lambda Layer ARN from build stage
      required: false
      value: ""
  stages:
    - stage:
        name: Build Lambda Layer
        identifier: build_lambda_artifacts
        description: Build and publish Lambda layer with dependencies
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: eksconnector
              namespace: harness-delegate-ng
              serviceAccountName: helm-delegate
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Lambda Layer
                  identifier: build_lambda_layer
                  spec:
                    connectorRef: eksconnector
                    image: python:3.13-slim
                    shell: Bash
                    command: |-
                      set -e

                      echo "Installing AWS CLI..."
                      apt-get update && apt-get install -y zip awscli curl

                      echo "Configuring AWS CLI for pod identity..."
                      # Configure AWS CLI for pod identity
                      export AWS_REGION=us-east-1
                      export AWS_DEFAULT_REGION=us-east-1

                      # Test AWS credentials (pod identity should handle authentication automatically)
                      echo "Testing AWS credentials..."
                      aws sts get-caller-identity

                      echo "Building Lambda layer from requirements.txt..."
                      cd my_lambda

                      # Create layer directory structure
                      mkdir -p python/lib/python3.13/site-packages

                      # Install dependencies to the layer directory
                      pip install -r requirements.txt -t python/lib/python3.13/site-packages/

                      # Package the layer
                      zip -r layer.zip python/

                      echo "Publishing Lambda layer directly..."
                      LAYER_ARN=$(aws lambda publish-layer-version \
                        --layer-name my-lambda-dependencies-layer-ammar \
                        --description "Lambda layer with dependencies from requirements.txt" \
                        --zip-file fileb://layer.zip \
                        --compatible-runtimes python3.13 \
                        --region us-east-1 \
                        --query 'LayerVersionArn' \
                        --output text)

                      echo "Layer ARN: $LAYER_ARN"
          caching:
            enabled: false
        delegateSelectors:
          - helm-delegate
    - stage:
        name: deploylambda
        identifier: deploylambda
        description: ""
        type: Deployment
        spec:
          deploymentType: AwsLambda
          service:
            serviceRef: lambdaservice
            serviceInputs:
              serviceDefinition:
                type: AwsLambda
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: devtest
            gitBranch: master
            deployToAll: false
            infrastructureDefinitions:
              - identifier: devtestinfra
          execution:
            steps:
              - step:
                  name: Deploy Aws Lambda
                  identifier: deployawslambda
                  type: AwsLambdaDeploy
                  timeout: 10m
                  spec: {}
            rollbackSteps:
              - step:
                  name: Aws Lambda rollback
                  identifier: awslambdarollback
                  type: AwsLambdaRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        delegateSelectors:
          - helm-delegate
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
